from django.urls import path
from knox import views as knox_views
from . import views_acc, views_store, views_buyer

urlpatterns = [
    path('acc_register', views_acc.RegisterAPI.as_view()),
    path('acc_login', views_acc.LoginAPI.as_view()),
    path('get_profile', views_acc.ProfileGetView.as_view()),
    path('profile_update', views_acc.ProfileUpdateView.as_view()),
    path('acc_logout', views_acc.Logout.as_view()),
    path('latest_store_registration_subscription_price', views_store.SubscriptionPriceGetView.as_view()),
    path('available_quantity_types_for_product', views_store.QuantityTypesView.as_view()),
    path('register_store', views_store.RegisterStoreView.as_view()),
    path('update_store', views_store.StoreUpdateView.as_view()),
    path('generate_own_store_referal_code', views_store.StoreRefCodeGenView.as_view()),
    path('own_store_details', views_store.StoreStrDetailsView.as_view()),
    path('store_details_showed_to_customer/<int:store_id>/', views_store.StoreUsrDetailsView.as_view()),
    path('stores_list_view_for_customer', views_store.StoresListView.as_view()),
    path('delete_store', views_store.StoreDeleteView.as_view()),
    path('create_category_for_store', views_store.CategoryCreateView.as_view()),
    path('update_category_for_store/<int:categ_id>/', views_store.CategoryUpdateView.as_view()),
    path('fmcg_products_list_showed_to_store', views_store.FMCGProductsListView.as_view()),
    path('single_fmcg_product_showed_to_store/<int:fmcg_id>/', views_store.FMCGProductGetView.as_view()),
    path('create_fmcg_transaction', views_store.FMCGTrnsctnCreateView.as_view()),
    path('list_personal_fmcg_transactions', views_store.FMCGTrnsctnsListView.as_view()),
    path('categories_showed_to_store_during_product_creation_or_update', views_store.CategoriesProductPageDetailsView.as_view()),
    path('create_product', views_store.ProductCreateView.as_view()),
    path('update_product/<int:product_id>/', views_store.ProductUpdateView.as_view()),
    path('refill_product_stock/<int:product_id>/', views_store.RefillQuantityInStockView.as_view()),
    path('single_product_detail/<int:product_id>/', views_store.ProductGetDetailsView.as_view()),
    path('delete_product', views_store.ProductDeleteView.as_view()),
    path('categories_with_products_showed_on_store_page/<int:store_id>/', views_store.CategoriesOnStorePageDetailsView.as_view()),
    path('chosen_category_with_products_showed_on_store_page/<int:categ_id>/', views_store.SingleCategoryOnStorePageDetailsView.as_view()),
    path('delete_category_along_with_its_products', views_store.CategoryDeleteView.as_view()),
    path('generate_coupon_for_store', views_store.CouponGenView.as_view()),
    path('list_all_generated_coupons_of_a_store', views_store.CouponsGetView.as_view()),
    path('delete_coupon', views_store.CouponDeleteView.as_view()),
    path('place_order', views_buyer.OrderCreateView.as_view()),
    path('accept_order', views_buyer.OrderAcceptView.as_view()),
    path('select_payment_and_save_cart_preference', views_buyer.SelectPaymentAndSaveCartView.as_view()),
    path('list_order_tracking_stages_and_options', views_buyer.OrderTrackingStagesListView.as_view()),
    path('update_order_tracking_stage', views_buyer.UpdateOrderTrackingStageView.as_view()),
    path('list_all_orders_of_customer', views_buyer.CartOrdersCstmrListView.as_view()),
    path('list_all_saved_orders_of_customer', views_buyer.SavedOrdersListView.as_view()),
    path('single_order_detail_showed_to_customer/<int:cart_id>/', views_buyer.CartOrdersCstmrGetView.as_view()),
    path('list_all_orders_of_store', views_buyer.CartOrdersStrListView.as_view()),
    path('single_order_detail_showed_to_store/<int:cart_id>/', views_buyer.CartOrdersStrGetView.as_view()),
    path('list_all_coupons_used_by_customer', views_buyer.UsedCouponsListView.as_view()),
]